name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore ./WhatsDotLib.csproj

      - name: Build
        run: dotnet build ./WhatsDotLib.csproj --configuration Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack ./WhatsDotLib.csproj --configuration Release --no-build -o ./nupkg

      - name: Push to NuGet
        run: dotnet nuget push nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
